### ISSUE TITLE
What license is this code under?

### ISSUE THREAD

**Issue by alsuren** [tonarino/panel-firmware#16]
Hello.

I found this project via a link in your blog post (https://blog.tonari.no/rust-simple-hardware-project). Thank you for sharing your work.

I'm currently working on a refactor of the serial port protocol code for a project that I'm working on with my housemate (https://github.com/hoverkite/hoverkite/issues/5). I noticed that our current wire format is very similar to yours, but your code structure is much cleaner than ours.

I think it would be good to share ideas between our projects. [GitHub recommends adding a license to your repository, to make this easier](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository).

If you haven't decided on a license, I can recommend the Apache 2 + MIT scheme that the Rust compiler uses. A patch to add this license would look similar to this: https://github.com/hoverkite/hoverkite/commit/01fb3f7ab8d1eca9be7df2d5481eb69a03281158 . I can make a pull-request to do this if you would like.

David.

**Comment by bschwind** [comment]
Hi @alsuren ! Thanks for the reminder, I'm still not in the habit of attaching licenses to my new projects. I typically use the MIT license, I hope that works for your project.

#17
